{{- if .Values.variables.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blog-service-1.fullname" . }}
  labels:
    {{- include "blog-service-1.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.variables.secret | nindent 2 }}
{{- end }}